name:                blanks
version:             0.5.0
github:              "ejconlon/blanks"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2019 Eric Conlon"
category:            Language
synopsis:            Fill-in-the-blanks - A library factoring out substitution from ASTs

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/blanks#readme>

dependencies:
- base >=4.12 && <5
- adjunctions >=4.4 && <5
- containers >=0.6 && <1
- deepseq >=1.4 && <2
- distributive >=0.6 && <1
- microlens >= 0.4 && < 1
- mtl >=2.2 && <3

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- KindSignatures
- MultiParamTypeClasses
- PatternSynonyms
- Rank2Types
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

tests:
  blanks-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blanks
    - megaparsec
    - tasty
    - tasty-hunit
    - text
