name:                blanks
version:             0.2.0
github:              "ejconlon/blanks"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2019 Eric Conlon"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/blanks#readme>

dependencies:
- base >=4.12
- adjunctions >=4.4
- containers >=0.6
- distributive >=0.6
- mmorph >=1.1
- mtl >=2.2
- newtype-generics >=0.5

default-extensions:
- BangPatterns
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- KindSignatures
- MultiParamTypeClasses
- Rank2Types
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  blanks-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blanks

tests:
  blanks-test:
    main:                Tasty.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blanks
    - tasty
    - tasty-discover
    - tasty-hunit
